from github import Github
import os

def create_pull_request():

    g = Github(os.getenv("GITHUB_TOKEN"))

    repo = g.get_repo("username/repository")

    pr = repo.create_pull(
        title="Automated CI Fix",
        body="Patch generated by autonomous repair agent.",
        head="surgeon_agents",
        base="main"
    )

    print("PR created:", pr.html_url)